---

- name: generate self-signed SSL certs
  include_role:
    name: laprimaire.ssl-certs
  vars:
    ssl_cert_fqdn: "{{ ghost_fqdn }}"
  when: base_hostname != 'laprimaire.org'

- name: create ghost directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /srv/ghost
    - /srv/ghost/mysql-initdb.d
    - /data/ghost/content
    - /data/ghost/mysql

- name: template ghost docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /srv/ghost/docker-compose.yml

# ! FIXME: must be a symlink when working locally
- name: copy ghost content
  copy:
    src: ./content/
    dest: /data/ghost/content
  notify: restart ghost

- name: template analytics.js
  template:
    src: analytics.js.j2
    dest: /data/ghost/content/themes/lyra/assets/js/analytics.js
  notify: restart ghost

- name: copy ghost database
  copy:
    src: ./mysql-initdb.d/
    dest: /srv/ghost/mysql-initdb.d

- name: start ghost
  docker_compose:
    project_src: /srv/ghost
