---

- name: generate self-signed SSL certs
  include_role:
    name: laprimaire.ssl-certs
  vars:
    ssl_cert_fqdn: "{{ monitoring_fqdn }}"
  when: base_hostname != 'laprimaire.org'
  loop:
    - "{{ monitoring_fqdn }}"
    - "{{ metrics_fqdn }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /srv/monitoring

- include: prometheus.yml

- include: grafana.yml

- name: template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /srv/monitoring/docker-compose.yml

- name: start monitoring
  docker_compose:
    project_src: /srv/monitoring
