---

- name: generate self-signed SSL certs
  include_role:
    name: laprimaire.ssl-certs
  vars:
    ssl_cert_fqdn: "{{ monitoring_fqdn }}"
  when: base_hostname != 'laprimaire.org'

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/monitoring

- name: create mounted directories
  file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx
  loop:
    - /data/grafana/
    - /data/prometheus/

- name: template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/monitoring/docker-compose.yml

- name: start monitoring
  docker_compose:
    project_src: /opt/monitoring
