---

- name: generate self-signed SSL certs
  include_role:
    name: laprimaire.ssl-certs
  vars:
    ssl_cert_fqdn: "sso.infra.{{ base_hostname }}"
  when: base_hostname != 'laprimaire.org'

- name: create nginx directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/nginx
    - /opt/nginx/certs
    - /opt/nginx/vhost.d

- name: template nginx docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/nginx/docker-compose.yml
  notify: restart nginx-proxy

- name: enable vouch vhosts
  block:
    - template:
        src: vouch.conf.j2
        dest: "/opt/nginx/vhost.d/{{ hostvars[item]['ansible_host'] }}"
      loop: "{{ groups['infra'] }}"
      notify: restart nginx-proxy
    - template:
        src: vouch_location.conf.j2
        dest: "/opt/nginx/vhost.d/{{ hostvars[item]['ansible_host'] }}_location"
      loop: "{{ groups['infra'] }}"
      notify: restart nginx-proxy
  when: vouch_enabled | bool

- name: disable vouch vhosts
  block:
    - file:
        path: "/opt/nginx/vhost.d/{{ hostvars[item]['ansible_host'] }}"
        state: absent
      loop: "{{ groups['infra'] }}"
      notify: restart nginx-proxy
    - file:
        path: "/opt/nginx/vhost.d/{{ hostvars[item]['ansible_host'] }}_location"
        state: absent
      loop: "{{ groups['infra'] }}"
      notify: restart nginx-proxy
  when: not (vouch_enabled | bool)

- name: start nginx reverse-proxy
  docker_compose:
    project_src: /opt/nginx
