all:
  hosts:
    laprimaire_2022:
      ansible_host: "{{ lookup('env', 'LAPRIMAIRE_2022_HOST') | default('192.168.142.2', true) }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'LAPRIMAIRE_2022_SSH_KEY') | default('/vagrant/.vagrant/machines/laprimaire_2022/virtualbox/private_key', true) }}"
      ansible_ssh_user: root
      ansible_become: yes
