---

- name: restart monitoring
  shell: docker-compose restart
  args:
    chdir: /srv/monitoring

- name: restart prometheus
  shell: docker-compose restart prometheus
  args:
    chdir: /srv/monitoring

- name: restart grafana
  shell: docker-compose restart grafana
  args:
    chdir: /srv/monitoring
