---

- name: install openssl
  apt:
    name: openssl
    state: present

- name: create /opt/nginx/certs
  file:
    path: /opt/nginx/certs
    state: directory

- name: create self-signed certificate
  shell: |
    openssl req -new -nodes -x509 -extensions v3_ca \
      -subj "/C=FR/ST=IdF/L=Paris/O=IT/CN={{ ssl_cert_fqdn }}" \
      -days 3650 \
      -keyout /opt/nginx/certs/{{ ssl_cert_fqdn }}.key \
      -out /opt/nginx/certs/{{ ssl_cert_fqdn }}.crt 
  args:
    creates: "/opt/nginx/certs/{{ ssl_cert_fqdn }}.crt"
